project:
  type: website

website:
  google-analytics: "G-F8NWF32PC7"
  cookie-consent: true
  announcement:
    icon: info-circle
    dismissable: true
    content: "Welcome to our new home focused on our work for Fred Hutch data efforts! Our [Hutch Data Science site is still live](https://hutchdatascience.org/) and is being focused on training and community resources that include and extend beyond the Fred Hutch."
    type: dark
    position: above-navbar
  page-footer:
    left: "Contact us by scheduling a [Data House Call](programs/dhc.qmd)"
    right:
      - icon: house-gear-fill
        href: programs/dhc.qmd
      - icon: github
        href: https://github.com/getwilds

  page-navigation: true
  search:
    location: navbar
    type: textbox
  favicon: /img/favicon.png
  open-graph: true
  navbar:
    logo: img/Fred-Hutch-Logo-Primary.png
    logo-alt: "Logo for Fred Hutch Cancer Center"
    right:
      - text: "Get Help"
        href: programs/dhc.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Our Team"
        href: about.qmd


  sidebar:
      style: "floating"
      search: false
      contents:
        - text: "Home"
          href: index.qmd
        - text: "Our Team"
          href: about.qmd         
        - section: "What we Do"
          contents:
            - text: "Data Strategy"
              href: strategy.qmd
            - text: "Data Governance"
              href: gov.qmd
            - text: "Translational Data Science & Software"
              href: dss.qmd
            - text: "Training & Community"
              href: training.qmd
            - text: "Translational Applications & Tools"
              href: tools.qmd
            - text: "Data Partnerships"
              href: partnerships.qmd
        - section: "Our Resources"
          href: resources.qmd
          contents:
            - text: "Data House Calls"
              href: programs/dhc.qmd
            - text: "Learning Communities"
              href: programs/communities.qmd
            - section: "WILDS"
              href: programs/wilds.qmd
              contents: 
                - text: Collaborative Projects
                  href: programs/wildscp.qmd
            - text: "SciWiki"
              href: programs/sciwiki.qmd
            - text: "Fred Hutch Data Slack"
              href: https://join.slack.com/t/fhdata/signup
            - text: "Monday Morning Data Science"
              href: https://fhdata.substack.com/
            - text: "Events"
              href: https://centernet.fredhutch.org/u/data-science-lab.html
            - text: "Our Partners"
              href: https://research.fredhutch.org/data/en.html

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - styles.scss
    link-color: '#00ABC8'
    fontsize: 1.1em
    toc: false
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true


